services:
  backend:
    build: ./be
    ports:
      - "3001:3001"
    env_file:
      - ./be/.env
    volumes:
      - ./be:/app
    depends_on:
      - db
    restart: unless-stopped

  frontend:
    build: ./fe
    ports:
      - "3000:3000"
    env_file:
      - ./fe/.env
    volumes:
      - ./fe:/app
    depends_on:
      - backend
    restart: unless-stopped

  db:
    image: mysql:8.0
    restart: unless-stopped
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: rootpass123
      MYSQL_DATABASE: forex
      MYSQL_USER: user
      MYSQL_PASSWORD: userpass123
      TZ: Asia/Kuala_Lumpur
    command: --default-time-zone='+08:00'
    volumes:
      - db-data:/var/lib/mysql
      - ./be/init.sql:/docker-entrypoint-initdb.d/init.sql

volumes:
  db-data:
