import type { Metadata } from "next";
import "./globals.css";
import { IsMobileProvider } from "@/context/isMobileContext";

export const metadata: Metadata = {
  title: "Forex Coding Challenge by Zac",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className="bg-gray-200">
        <IsMobileProvider>
          {children}
        </IsMobileProvider>
      </body>
    </html>
  );
}
